services:
  - type: web
    name: advhub-dashboard-backend
    env: node
    region: oregon
    plan: starter
    buildCommand: pnpm install --prod=false && pnpm run build
    startCommand: pnpm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
    healthCheckPath: /api
